import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
const cityList = [
  {
    country: "USA",
    city: "NewYork",
  },
  {
    country: "Spain",
    city: "Madrid",
  },
  {
    country: "England",
    city: "London",
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/about">
          <a>About App</a>
        </Link>
      </div>

      <hr />
      <div>
        <ul>
          {cityList.map((item, index) => (
            <li key={index}>
              <Link href={`/${item.country}/${item.city}`}>
                <a>
                  {item.country}-{item.city}
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
